export const MENU = [
  {
    menuCode: "000",
    menuName: "Sample",
    parentMenu: undefined,
    open: false,
  },
  {
    menuCode: "010",
    menuName: "Component Sample",
    parentMenu: "000",
    url: "common/Samples/ComponentSample",
    open: false,
    search: true,
    add: true,
    remove: true,
    save: true,
    excel: true,
    report: true,
  },
  {
    menuCode: "020",
    menuName: "Form Sample",
    parentMenu: "000",
    url: "common/Samples/FormSample",
    open: false,
    search: true,
    add: true,
    remove: true,
    save: true,
    excel: true,
    report: true,
  },
];
