export const MENU = [
  {
    menuCode: "0000",
    menuName: "Sample",
    parentMenu: undefined,
    open: false,
  },
  {
    menuCode: "0100",
    menuName: "Components",
    parentMenu: "0000",
    open: false,
  },
  {
    menuCode: "0200",
    menuName: "Form",
    parentMenu: "0000",
    open: false,
  },
  {
    menuCode: "0101",
    menuName: "ButtonGroup Sample",
    parentMenu: "0100",
    url: "common/samples/PageHeaderSample",
    open: false,
    search: true,
    add: true,
    remove: true,
    save: true,
    excel: true,
    report: true,
  },
  {
    menuCode: "0102",
    menuName: "Button Sample",
    parentMenu: "0100",
    url: "common/samples/ButtonSample",
    open: false,
  },
  {
    menuCode: "0103",
    menuName: "InputBox Sample",
    parentMenu: "0100",
    url: "common/samples/InputBoxSample",
    open: false,
  },
  {
    menuCode: "0104",
    menuName: "Textarea Sample",
    parentMenu: "0100",
    url: "common/samples/TextareaSample",
    open: false,
  },
  {
    menuCode: "0105",
    menuName: "Select Sample",
    parentMenu: "0100",
    url: "common/samples/SelectSample",
    open: false,
  },
  {
    menuCode: "0106",
    menuName: "Check Sample",
    parentMenu: "0100",
    url: "common/samples/CheckSample",
    open: false,
  },
  {
    menuCode: "0107",
    menuName: "Radio Sample",
    parentMenu: "0100",
    url: "common/samples/RadioSample",
    open: false,
  },
  {
    menuCode: "0108",
    menuName: "DateTimePicker Sample",
    parentMenu: "0100",
    url: "common/samples/DateTimePickerSample",
    open: false,
  },
  {
    menuCode: "0109",
    menuName: "Loading Sample",
    parentMenu: "0100",
    url: "common/samples/LoadingSample",
    open: false,
  },
  {
    menuCode: "0110",
    menuName: "Tab Sample",
    parentMenu: "0100",
    url: "common/samples/TabSample",
    open: false,
  },
  {
    menuCode: "0201",
    menuName: "Form Sample",
    parentMenu: "0200",
    url: "common/samples/FormSample",
    open: false,
  },
  {
    menuCode: "0202",
    menuName: "Component Sample",
    parentMenu: "0200",
    url: "common/samples/ComponentSample",
    open: false,
    search: true,
    add: true,
    remove: true,
    save: true,
    excel: true,
    report: true,
  },
];
